### ISSUE TITLE
Polars Columns Definition Error

### ISSUE THREAD

**Issue by Msoliman-waleed** [moritzwilksch/pyfin-sentiment#3]
Hi mate, thank you for the hard work , well done.
i tried to run the model under Python 3.11 , however Polars return the following error:

DataFrame.__init__() got an unexpected keyword argument 'columns'

i think according to current Polars docs, this line in your code should be change:
df = pl.DataFrame(texts, columns=["text"])
To be as following:
df = pl.DataFrame({"text":texts})

once this change is done , i think another error regarding the withColumn function as it should be renamed to be withColumns instead.

cheers

**Comment by amritkundan** [comment]
I changed the line of code to df = pl.DataFrame({"text":texts})
but I am still running into the same error. I am also having trouble finding the withColumn function you are talking about.

**Comment by moritzwilksch** [comment]
fixed this and bumped the polars version, give it a shot with the new `0.1.1` version
